Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -2,6 +2,7 @@ name: pre-commit
 
 on:
   pull_request:
+    branches: [main]
   push:
     branches: [main]
 
@@ -12,3 +13,6 @@ jobs:
     - uses: actions/checkout@v1
     - name: set msg
       run: echo "welcome"
+    # Intentional fail step for testing purposes
+    - name: fail check
+      run: exit 1
